### ISSUE TITLE
方舟抽取，然后发现了报错

### ISSUE THREAD

**Issue by LSGLSH** [sophisticate9008/draw_helper#1]
![Screenshot_2022-08-29-13-54-39-919_com sonelli juicessh](https://user-images.githubusercontent.com/106002475/187132879-69d26252-de61-4895-9746-32db9b7da511.jpg)

**Comment by sophisticate9008** [comment]
更新干员数据了吗

**Comment by LSGLSH** [comment]
> 更新干员数据了吗

更新了
