### ISSUE TITLE
小BUG？

### ISSUE THREAD

**Issue by Nenot233** [sophisticate9008/draw_helper#3]
![XTA5 FTZ4SQC19T9{D9MK%A](https://user-images.githubusercontent.com/108965579/198309607-fa3408a6-d70e-4ab3-a178-a0c383c8d3be.png)
![IX6)UB1QGR$BV5VMKM% JE0](https://user-images.githubusercontent.com/108965579/198309624-7fa8e5a9-901e-4922-b71a-5cf9a2d6451f.png)
当语音未出来时，可以触发两次猜语音，结束时强行算正确两条（可能可以更多）

**Comment by sophisticate9008** [comment]
是之前语音没加重复试错，所以阻断放在了发出后
